### ISSUE TITLE
Duplicate links to the `docs/index.md` in navigation drawer

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmos.org-EXPERIMENTAL#15]
This is a side-effect arose somewhere in the course of resolving #8, possibly probably with bfae288:

![image](https://user-images.githubusercontent.com/5556545/145506257-8f7b5938-f226-4abb-8938-7ceaa6decb43.png)

The second "farmOS.js Docs" menu item is an unnecessary duplicate, since it's the same as the "Getting started". The `docs/index.md` page for farmOS is not duplicated, but it would be better if the "farmOS 2.x Docs" was instead "Introduction" or something similar.

Ultimatley, this is all more fallout from adopting `mkdcos.yml` as our main configuration file for this site. MkDocs doesn't require it to actually specify a title for the `docs/index.md` file, or even list it in the `nav` section, since it is assumed to be the root of the website, and the title is essentially just the `site_name`. This is how the [farmOS `mkdocs.yml`](https://github.com/farmOS/farmOS/blob/0e44fdafe684c53123a3628537273d21721e5907/mkdocs.yml) is structured, but the [`farmOS.js `config.yml`](https://github.com/farmOS/farmOS.js/blob/9fc0b72c26b1141f8ad4c759cf83843f46d1a49f/docs/config.yml) is not.

I think this might take some adjustment in different places. Obviously, the logic for the navigation drawer should be using the "Getting started" title, but it would be ideal if the farmOS `mkdocs.yml` specified the title of its own `docs/index.md` page, so we aren't reusing the "farmOS 2.x Docs" title, as we are in so many places in that above screenshot.

**Comment by jgaehring** [comment]
Ok, this had a pretty simple solution, which was pretty much deleting lines 95-98 from the return value of the `fromMkdocsYaml` function:

https://github.com/farmOS/farmos.org-EXPERIMENTAL/blob/bac140af6fdf7e49c49b1bfcd92e4f1449c7ace9/src/navigation.js#L92-L100

Basically, those lines were a kind of a workaround for the way MkDocs didn't require the `docs/index.md` to be listed in the `nav` object, fixing it by explicitly declaring the root path as the parent of all the rest of the navigation nodes. This worked fine when farmOS was the only source repo, but it creates a duplicate for the farmOS.js repo since the `docs/index.md` path is in fact listed in my `config.yml`'s `nav` object.

One important item of note: if I delete those lines above, which I believe is the correct solution, the farmOS repository no longer has a link to the `docs/index.md` page. @mstenta, I gather that page was kind of a placeholder anyways, correct? We can add that warning or something like it to the `pages/index.js` page, which will be our new home page for farmos.org. It would make sense to have some kind of intro or "Getting started" page to the farmOS docs, but that could be added to the `mkdocs.yml` as:

```yml
nav:
  - Getting started: index.md
  - Data model:
    - Introduction: model/index.md
    - Record types:
      - Assets: model/type/asset.md
      - Logs: model/type/log.md
      # etc...
```

What do you think? We probably also want to discuss whether it makes sense to have an intro page for _all_ the docs, separate from the home page, but that's for a later discussion.

**Comment by mstenta** [comment]
> the farmOS repository no longer has a link to the `docs/index.md` page. @mstenta, I gather that page was kind of a placeholder anyways, correct?

Yes, that's correct. We can remove that entirely from the farmOS repo - or create a true index with the new context in mind.

**Comment by mstenta** [comment]
Perfect! I'll add that to my list.
