### ISSUE TITLE
More source repos?

### ISSUE THREAD

**Issue by jgaehring** [farmOS/farmos.org-EXPERIMENTAL#17]
Do we want to add any other farmOS projects to [`source-repos.js`](https://github.com/farmOS/farmos.org-EXPERIMENTAL/blob/bac140af6fdf7e49c49b1bfcd92e4f1449c7ace9/source-repos.js) before we launch this on farmos.org?

@paul121, ready to give it a try with the farmOS.py docs? Or @symbioquine, with farmOS-map?

**Comment by paul121** [comment]
Yes! Let's give it a go!

**Comment by jgaehring** [comment]
Great!

So the basic rundown is:

1. Add a GitHub Action to the farmOS.py repo, something like the [`netlify-build-docs.yml`](https://github.com/farmOS/farmOS.js/blob/main/.github/workflows/netlify-build-docs.yml) workflow I have in farmOS.js (I'd welcome any improvements to this GHA, too, if you know any better ways to handle the environment variables).
2. Add farmOS.py to the [`source-repos.js`](https://github.com/farmOS/farmos.org-EXPERIMENTAL/blob/main/source-repos.js), with the configuration you want for those docs. I'm happy to walk through the config options with you when you're ready.

The main issue I foresee is that you still have a lot of details about installation etc in your README. We can probably accommodate that with some additional config options, or you could move parts of that to your `docs/` directory, up to you. Again, I'm happy to work with you on that however you prefer to do it. This will be a good chance for me to hammer out the configuration and document it as best as I can in this project's own README (or do I set up a `docs/` directory here as well???).

Just let me know if and when you want to a walkthrough, or feel free to give it go on your own and just open a PR when you're ready.

**Comment by jgaehring** [comment]
We can and will be adding more sources, but for now I believe the purpose of this issue has been fulfilled.
